## Задание
 Дана целочисленная квадратная матрица. Определить:
произведение элементов в тех строках, которые не содержат отрицательных элементов;
максимум среди сумм элементов диагоналей, параллельных главной диагонали матрицы.


In [104]:
import numpy as np

m = np.matrix('1 0 3; 5 2 6; 9 -9 5') #зададим квадратную матрицу
print(m)
md = m 
md = np.where(m >= 0, True, False)
print(md)
md = md.prod(axis = 1)#                 создадим мод для матриц
print(md)
md = np.where(md > 0, True, False)#
mo = m.prod(axis = 1)
print(md)
print ("\nПроизведение элементов в тех строках, которые не содержат отрицательных элементов")
print (mo[md])

[[ 1  0  3]
 [ 5  2  6]
 [ 9 -9  5]]
[[ True  True  True]
 [ True  True  True]
 [ True False  True]]
[1 1 0]
[ True  True False]

Произведение элементов в тех строках, которые не содержат отрицательных элементов
[[ 0]
 [60]]


*Найдем максимум среди сумм элементов диагоналей, параллельных главной диагонали матрицы.*

In [86]:
dd = np.array([np.trace (m, offset = -2),np.trace (m, offset = -1),np.trace (m, offset = 1),np.trace (m, offset = 2)])

print(dd.max())

14
