

# Лабораторная работа 3.2. Знакомство с NumPy
Библиотека NumPy -- быстрая библиотека для математики в Python, основная структура данных -- массив `numpy.array`:

![](https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif)

In [3]:
# подключение модуля numpy под именем np
import numpy as np

In [4]:
# основная структура данных - массив
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

print("a =", a)
print("b =", b)

a = [1 2 3 4 5]
b = [0.1 0.2 0.3 0.4 0.5]


Создайте массив с 5 любыми числами:

In [5]:
m = np.array([6,7,8,9,0])
print ("m =",m)

m = [6 7 8 9 0]


Арифметические операции, в отличие от операций над списками, применяются поэлементно:

In [6]:
list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

print("list1:", list1)
print('\tlist1 * 3:', list1 * 3)
print('\tlist1 + [1]:', list1 + [1])

print('array1:', array1)
print('\tarray1 * 3:', array1 * 3)
print('\tarray1 + 1:', array1 + 1)

list1: [1, 2, 3]
	list1 * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
	list1 + [1]: [1, 2, 3, 1]
array1: [1 2 3]
	array1 * 3: [3 6 9]
	array1 + 1: [2 3 4]


Создайте массив из 5 чисел. Возведите каждый элемент массива в степень 3

In [7]:
print(m**3)

[216 343 512 729   0]


Если в операции участвуют $2$ массива (по умолчанию -- одинакового размера), операции считаются для соответствующих пар:

In [ ]:
print("a + b =", a + b)
print("a * b =", a * b)

In [ ]:
# вот это разность
print("a - b =", a - b)

# вот это деление
print("a / b =", a / b)

# вот это целочисленное деление
print("a // b =", a // b)

# вот это квадрат
print("a ** 2 =", a ** 2)

 Создайте два массива одинаковой длины. Выведите массив, полученный делением одного массива на другой.

In [15]:
aa = np.array([2,3,2,2])
b = np.array([4,6,6,10])
print(b/aa)

[2. 2. 3. 5.]


#### *Л — логика*
К элементам массива можно применять логические операции.

Возвращаемое значение -- массив, содержащий результаты вычислений для каждого элемента (`True` -- "да" или `False` -- "нет"):

In [ ]:
print("a =", a)
print("\ta > 1: ", a > 1)
print("\nb =", b)
print("\tb < 0.5:  ", b < 0.5)

print("\nОдновременная проверка условий:")
print("\t(a > 1) & (b < 0.5):  ", (a>1) & (b < 0.5))
print("А вот это проверяет, что a > 1 ИЛИ b < 0.5:  ", (a > 1) | (b < 0.5))

Создайте 2 массива из 5 элементов. Проверьте условие "Элементы первого массива меньше 6, элементы второго массива делятся на 3"

In [19]:
d = np.array([6,7,8,9,0])
c = np.array([3,6,9,9,12])
print(d<6)
print(c%3 == 0)

[False False False False  True]
[ True  True  True  True  True]


Теперь проверьте условие "Элементы первого массива делятся на 2 или элементы второго массива больше 2"

In [21]:
print((d%2) | (c > 2))

[1 1 1 1 1]


Зачем это нужно? Чтобы выбирать элементы массива, удовлетворяющие какому-нибудь условию:

In [23]:
print("a =", a)
print("a > 2:", a > 2)
# индексация - выбираем элементы из массива в тех позициях, где True
print("a[a > 2]:", a[a > 2])

d = [1 2 3 4 5]
d > 2: [ True  True  True  True False]
d[d > 2]: [6 7 8 9]


Создайте массив с элементами от 1 до 20. Выведите все элементы, которые больше 5 и не делятся на 2

Подсказка: создать массив можно с помощью функции np.arange(), действие которой аналогично функции range, которую вы уже знаете.

In [24]:
e = np.arange(1,5,1)
print("e =", e)
print("e > 5:", e > 5)
# индексация - выбираем элементы из массива в тех позициях, где True
print("e[e%2 != 0]:", e[e%2 != 0])

e = [1 2 3 4]
e > 5: [False False False False]
e[e%2 != 0]: [1 3]


#### А ещё NumPy умеет...

Все операции NumPy оптимизированы для быстрых вычислений над целыми массивами чисел и в методах `np.array` реализовано множество функций, которые могут вам понадобиться:

In [ ]:
# теперь можно считать средний размер котиков в одну строку!
print("np.mean(a) =", np.mean(a))
# минимальный элемент
print("np.min(a) =", np.min(a))
# индекс минимального элемента
print("np.argmin(a) =", np.argmin(a))
# вывести значения массива без дубликатов
print("np.unique(['male', 'male', 'female', 'female', 'male']) =", np.unique(['male', 'male', 'female', 'female', 'male']))

# и ещё много всяких методов
# Google в помощь

---

---

Пора еще немного потренироваться с NumPy.

Выполните операции, перечисленные ниже:

In [ ]:
print("Разность между a и b:", a - b
     )
print("Квадраты элементов b:", b**2
     )
print("Половины произведений элементов массивов a и b:", a*b
     )

print()
print("Максимальный элемент b:", np.max(b)
     )
print("Сумма элементов массива b:", np.sum(b)
     )
print("Индекс максимального элемента b:", np.argmax(b)
     )

 Задайте два массива: [5, 2, 3, 12, 4, 5]   и   ['f', 'o', 'o', 'b', 'a', 'r']

Выведите буквы из второго массива, индексы которых соответствуют индексам чисел из первого массива, которые больше 1, меньше 5 и делятся на 2

In [26]:
a1 = np.array([5,2,3,12,4,5])
b1 = np.array(['f','o','o','b','a','r'])
print(b1[(a1 > 1) & (a1 < 5) & (a1 % 2 == 0)])

['o' 'a']
